Allow cloning ECPublicKey and make its fields pub
LedgerHQ/ledger-device-rust-sdk pull request #135
Opened 2024-02-22 02:10 UTC by dfordivam

The contents of the public key are already pub, so it should be ok to clone it.

2024-02-22 08:54 UTC, yogh333 reviewed
LGTM

2024-02-22 08:56 UTC, yogh333 commented
Also could you please bump version 1.5.2 for `ledger_device_sdk` ?

2024-02-27 06:43 UTC, dfordivam commented
@yogh333 as part of this PR? (I suppose it should be done separately no?)

2024-02-27 09:15 UTC, yogh333 requested changes
@dfordivam yes bump of new version will be made later. In the meantime, could you please rebase your branch 🙏

2024-02-28 08:23 UTC, yogh333 approved these changes

2024-02-28 08:24 UTC, merged